version: "3.8"
services:
  mysql:
    image: mysql:8.0
    command: --sql_mode=NO_ENGINE_SUBSTITUTION
    ports:
      - "3306:3306"
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql