version: "3.8"
services:
  mysql:
    image: mysql:latest
    command: --sql_mode=NO_ENGINE_SUBSTITUTION
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bulbshare-tech-challenge
      MYSQL_ROOT_PASSWORD: 'root'
    restart: always
